format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_RH707_Evaluation_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '30', y: '160', id: BSP_SAM_RH707_Evaluation_Kit}
