package:
  format-version: "1.0.0"
  name: "core_apps_sam_rh707"
  version: "v3.3.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.23.0"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "V11.1.0"
